### PR TITLE
synchronizeid tmp_file

### PR DESCRIPTION
**Pull request by dsuket**
fix multi thread bug.
related #4 #9

### CODE REVIEW

**Comment by suyograo** [comment]
@dsuket 
Hi, can you please perform step 2 of https://github.com/elasticsearch/logstash/blob/master/CONTRIBUTING.md#contribution-steps

**Comment by ojizero** [comment]
@suyograo @dsuket any updates or ETA on when will this be released ? we are running into production issues related to it

**Comment by josephlewis42** [comment]
@dsuket would you mind signing the CLA https://www.elastic.co/contributor-agreement so we can get this merged? 

It's an awesome bit of work that would fix a few of the critical bugs in the plugin

**Comment by josephlewis42** [comment]
The fix for this has been released as part of logstash-output-google_bigquery version 4.0.0. 

**WARNING** 4.0.0 has breaking changes so [read the changelog](https://github.com/logstash-plugins/logstash-output-google_bigquery/blob/master/CHANGELOG.md) before upgrading to understand how they'll affect you.

The plugin can be updated with the following command

```
bin/logstash-plugin update logstash-input-google_pubsub
```

**Pull request closed without merging**
