### PR TITLE
Add support for specifying schema as a hash.

### PR DESCRIPTION
**Pull request by thesamet**
Some of the fields in our schema are nested or repeated. It would be nice to have a way to upload structured data to BigQuery.

### CODE REVIEW

**Comment by vgeshel** [comment]
+1 This is really essential to this plugin being useful.

**Comment by thesamet** [comment]
Any comments on this pull request?

**Comment by suyograo** [comment]
@thesamet would it be possible for you to  add tests for your changes please?

**Comment by suyograo** [comment]
@thesamet also can you sign the CLA? https://github.com/elasticsearch/logstash/blob/master/CONTRIBUTING.md#contribution-steps

**Comment by thesamet** [comment]
@suyograo I signed the CLA on July 9th and today (July 24).

While I would love to have tests for my change, this is the current state of the tests for this plugin: https://github.com/logstash-plugins/logstash-output-google_bigquery/blob/b1c4c5e739471cae08062c9379c0d7537720411e/spec/outputs/google_bigquery_spec.rb

I think the next step with this plugin when it comes to testing is for its base functionality.

**Comment by suyograo** [comment]
@thesamet thanks. You signed the cla using your gmail address. This patch is from trueaccord.com email. The PR email and CLA email needs to be the same

**Comment by thesamet** [comment]
@suyograo Signed under the company email address. Thanks!

**Comment by suyograo** [comment]
@thesamet weird.. I don't see it in our list. Will check back later. Thanks!

**Comment by thesamet** [comment]
@suyograo - I found that an additional github account I own (nadavsr) has been involved in this commit, so I signed the CLA for the third time mentioning that account too. Can you check?

**Comment by domudall** [comment]
Hi, is there an ETA for when this will be merged and updated?

**Comment by suyograo** [comment]
LGTM

**Comment by suyograo** [comment]
@domudall v2.0.3 has been published with these changes

**Comment by domudall** [comment]
Amazing, thank you!

**Pull request closed without merging**
